version: "3.8"
services:
  train:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - ${CONFIG}/:/config
      - ${DATA_PATH}/:/data
    entrypoint: python -m ap.train.server --config=./ap/utils/experiment_config.yml --data=/data

