# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ap.topic_model.v1 import TopicModelInference_pb2 as ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2


class TopicModelInferenceServiceStub(object):
    """инференс сервис
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDocumentsEmbedding = channel.unary_unary(
                '/ap.topic_model.v1.TopicModelInferenceService/GetDocumentsEmbedding',
                request_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2.GetDocumentsEmbeddingRequest.SerializeToString,
                response_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2.GetDocumentsEmbeddingResponse.FromString,
                )


class TopicModelInferenceServiceServicer(object):
    """инференс сервис
    """

    def GetDocumentsEmbedding(self, request, context):
        """получение векторных представлений документов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopicModelInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDocumentsEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentsEmbedding,
                    request_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2.GetDocumentsEmbeddingRequest.FromString,
                    response_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2.GetDocumentsEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ap.topic_model.v1.TopicModelInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TopicModelInferenceService(object):
    """инференс сервис
    """

    @staticmethod
    def GetDocumentsEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ap.topic_model.v1.TopicModelInferenceService/GetDocumentsEmbedding',
            ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2.GetDocumentsEmbeddingRequest.SerializeToString,
            ap_dot_topic__model_dot_v1_dot_TopicModelInference__pb2.GetDocumentsEmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
