# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ap.topic_model.v1 import TopicModelTrain_pb2 as ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2


class TopicModelTrainServiceStub(object):
    """сервис обучения моделей1
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDocumentsToModel = channel.unary_unary(
                '/ap.topic_model.v1.TopicModelTrainService/AddDocumentsToModel',
                request_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.AddDocumentsToModelRequest.SerializeToString,
                response_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.AddDocumentsToModelResponse.FromString,
                )
        self.UpdateModelConfiguration = channel.unary_unary(
                '/ap.topic_model.v1.TopicModelTrainService/UpdateModelConfiguration',
                request_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.UpdateModelConfigurationRequest.SerializeToString,
                response_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.UpdateModelConfigurationResponse.FromString,
                )
        self.StartTrainTopicModel = channel.unary_unary(
                '/ap.topic_model.v1.TopicModelTrainService/StartTrainTopicModel',
                request_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.StartTrainTopicModelRequest.SerializeToString,
                response_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.StartTrainTopicModelResponse.FromString,
                )
        self.TrainTopicModelStatus = channel.unary_unary(
                '/ap.topic_model.v1.TopicModelTrainService/TrainTopicModelStatus',
                request_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.TrainTopicModelStatusRequest.SerializeToString,
                response_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.TrainTopicModelStatusResponse.FromString,
                )


class TopicModelTrainServiceServicer(object):
    """сервис обучения моделей1
    """

    def AddDocumentsToModel(self, request, context):
        """загрузка документов для дообучения модели
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelConfiguration(self, request, context):
        """обновление конфигурации обучения
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrainTopicModel(self, request, context):
        """запуск дообучения
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainTopicModelStatus(self, request, context):
        """статус дообучения
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopicModelTrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDocumentsToModel': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocumentsToModel,
                    request_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.AddDocumentsToModelRequest.FromString,
                    response_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.AddDocumentsToModelResponse.SerializeToString,
            ),
            'UpdateModelConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelConfiguration,
                    request_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.UpdateModelConfigurationRequest.FromString,
                    response_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.UpdateModelConfigurationResponse.SerializeToString,
            ),
            'StartTrainTopicModel': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrainTopicModel,
                    request_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.StartTrainTopicModelRequest.FromString,
                    response_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.StartTrainTopicModelResponse.SerializeToString,
            ),
            'TrainTopicModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainTopicModelStatus,
                    request_deserializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.TrainTopicModelStatusRequest.FromString,
                    response_serializer=ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.TrainTopicModelStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ap.topic_model.v1.TopicModelTrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TopicModelTrainService(object):
    """сервис обучения моделей1
    """

    @staticmethod
    def AddDocumentsToModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ap.topic_model.v1.TopicModelTrainService/AddDocumentsToModel',
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.AddDocumentsToModelRequest.SerializeToString,
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.AddDocumentsToModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModelConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ap.topic_model.v1.TopicModelTrainService/UpdateModelConfiguration',
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.UpdateModelConfigurationRequest.SerializeToString,
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.UpdateModelConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartTrainTopicModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ap.topic_model.v1.TopicModelTrainService/StartTrainTopicModel',
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.StartTrainTopicModelRequest.SerializeToString,
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.StartTrainTopicModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainTopicModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ap.topic_model.v1.TopicModelTrainService/TrainTopicModelStatus',
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.TrainTopicModelStatusRequest.SerializeToString,
            ap_dot_topic__model_dot_v1_dot_TopicModelTrain__pb2.TrainTopicModelStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
