path_experiment: '/home/potapova/Projects/text_categorization/best_model'
path_wiki_train_batches: '/data/datasets/Antiplagiat/wiki_100/batches_train'
train_dict_path: '/data/datasets/Antiplagiat/train_with_combined_grnti_69_rubric_dict.joblib'
train_vw_path: '/data/datasets/Antiplagiat/train_with_combined_grnti_69_rubric.txt'
dictionary_path: '/data/datasets/Antiplagiat/dictionaties/dictionary_train_BPE_wiki_100_120k_11k.txt'
BPE_models: '/data/datasets/Antiplagiat/BPE_models'

# rubrics
num_rubric: 69
path_articles_rubrics_train_grnti: '/data/datasets/Antiplagiat/grnti_codes.json'
path_elib_train_rubrics_grnti: '/data/datasets/Antiplagiat/articles_train_val2/data_train/elib_train_grnti_codes.json'
path_grnti_mapping: '/data/datasets/Antiplagiat/grnti_to_number.json'

need_augmentation: False
aug_proportion: 0.2

# metrics parameters
metrics_to_calculate: ['analogy']
recalculate_train_centroids: True
path_train_thetas: '/data/datasets/Antiplagiat/combined_train/train_by_lang'
recalculate_test_thetas: True

artm_model_params:
  num_collection_passes: 25
  NUM_TOPICS: 125
  num_bcg_topic: 1
  tau_DecorrelatorPhi: 0.05
  tau_SmoothTheta: 0.025
  tau_SparseTheta: -0.1

MODALITIES_TRAIN:
  'GRNTI': 1
  'UDK': 1

LANGUAGES_TRAIN:
  'af': 1
  'am': 1
  'ar': 1
  'av': 1
  'az': 1
  'ba': 1
  'be': 1
  'bg': 1
  'bn': 1
  'bs': 1
  'ca': 1
  'ce': 1
  'cs': 1
  'cv': 1
  'cy': 1
  'da': 1
  'de': 1
  'el': 1
  'en': 1
  'eo': 1
  'es': 1
  'et': 1
  'eu': 1
  'fa': 1
  'fi': 1
  'fr': 1
  'gd': 1
  'gl': 1
  'gu': 1
  'he': 1
  'hi': 1
  'hr': 1
  'hu': 1
  'hy': 1
  'ia': 1
  'id': 1
  'inh': 1
  'is': 1
  'it': 1
  'ja': 1
  'jv': 1
  'ka': 1
  'kaa': 1
  'kbd': 1
  'kk': 1
  'kl': 1
  'km': 1
  'ko': 1
  'krc': 1
  'ky': 1
  'la': 1
  'lez': 1
  'lo': 1
  'lt': 1
  'lv': 1
  'mg': 1
  'mhr': 1
  'mi': 1
  'mk': 1
  'ml': 1
  'mn': 1
  'mo': 1
  'ms': 1
  'my': 1
  'myv': 1
  'ne': 1
  'nl': 1
  'no': 1
  'oc': 1
  'os': 1
  'pl': 1
  'pt': 1
  'rm': 1
  'rn': 1
  'ro': 1
  'ru': 1
  'sah': 1
  'sh': 1
  'si': 1
  'sk': 1
  'sl': 1
  'sm': 1
  'so': 1
  'sq': 1
  'sr': 1
  'sv': 1
  'sw': 1
  'ta': 1
  'tg': 1
  'th': 1
  'tk': 1
  'tr': 1
  'tt': 1
  'udm': 1
  'uk': 1
  'ur': 1
  'uz': 1
  'vi': 1
  'yi': 1
  'zh': 1
