name: documentation_builder

on:
  push:
    branches: [ add_documentation, develop, main ]
  pull_request:
    branches: [ add_documentation, develop, main ]

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -U sphinx
          pwd
          ls
          bash ../generate.sh

      - name: Build Docs
        run: |
          cd ./docs
          make clean html
