name: Docs
on: [push, pull_request]

jobs:
  build_documentation:
    name: "Build documentations on readthedocs.org"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -U sphinx
          pip install -r requirements.txt

      - name: Install Local Dependencies
        run: |
          ./generate.sh
          ls -la ap/topic_model/v1
          pwd

      - name: Build Docs
        run: |
          sphinx-build -b html ./docs/source/ public

      - uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: |
               ./docs/*
               ./ap/topic_model/v1/TopicModelBase_pb2.py
               ./ap/topic_model/v1/TopicModelBase_pb2_grpc.py
               ./ap/topic_model/v1/TopicModelInference_pb2.py
               ./ap/topic_model/v1/TopicModelInference_pb2_grpc.py
               ./ap/topic_model/v1/TopicModelTrain_pb2.py
               ./ap/topic_model/v1/TopicModelTrain_pb2_grpc.py
               ./ap/topic_model/v1/__init__.py

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
  
